name: Merge Schedule
on:
  pull_request:
    types:
      - opened
      - edited
      - synchronize
  schedule:
    - cron: 1 * * * *

jobs:
  merge_schedule:
    runs-on: ubuntu-latest
    steps:
      - uses: gr2m/merge-schedule-action
        with:
          merge_method: merge
          time_zone: "Europe/Madrid"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
